# ACTION METADATA
# https://docs.github.com/actions/creating-actions/metadata-syntax-for-github-actions

---
name: ghr-url
author: '@flex-development'
description: Create a URL for a GitHub registry
inputs:
  container:
    default: false
    description: generate url for container registry
    required: false
  pkg:
    default: ${{ github.event.repository.name }}
    description: package name
    required: false
  repo:
    default: ${{ github.repository }}
    description: github repository name (including owner)
    required: false
  server:
    default: ${{ github.server_url }}
    description: github server url
    required: false
outputs:
  url:
    description: the public registry url
    value: ${{ steps.url.outputs.result }}
runs:
  using: composite
  steps:
    - id: url
      shell: bash
      run: |
        set -e

        # init url type.
        TYPE=

        # generate url for container or package registry.
        [[ ${{ inputs.container }} == true ]] && TYPE=container || TYPE=npm

        # create registry url.
        URL=${{ inputs.server }}/${{ inputs.repo }}/pkgs/$TYPE/${{ inputs.pkg }}

        # set action output.
        echo "result=$(echo "$URL" | xargs)" >>$GITHUB_OUTPUT
branding:
  color: blue
  icon: link
